Bump up dependencies on pyserial and pyserial-asyncio
zigpy/zigpy-znp pull request #50
Opened 2020-12-11 11:55 UTC by Hedda

Bump up dependencies on pyserial and pyserial-asyncio for projects other projects that use this library but are not Home Assistant.

Adminiuga did the same dependency version bump for Home Assistant in https://github.com/home-assistant/core/pull/44089

pyserial-asyncio depends on pyserial and this bumps pyserial-asyncio to 0.5 version release and pyserial to 3.5 version release.

https://github.com/pyserial/pyserial-asyncio/releases/tag/v0.5

https://github.com/pyserial/pyserial/releases/tag/v3.5

2020-12-11 15:51 UTC, puddly requested changes
zigpy-znp doesn't depend on a specific version of these packages so can you change the `==` to `>=`?

2020-12-11 16:25 UTC, Adminiuga commented
I'm thinking it is just better to leave it as is, without any specific versioning??? There was nothing new in 3.5 or 0.5 which any of the radio lib requires. For non ZHA related projects, it would install the latest version anyway. For ZHA it is just better to control it from one place -- ZHA, since there are other integrations which pin pyserial and pyserial-asyncio, and pinning like in this PR would break compatibility with HA and cause those running  HA core issues

2020-12-11 16:40 UTC, puddly commented
I agree. Python doesn't install per-package dependencies so as long as some upstream library (i.e. ZHA) requires specific pyserial-asyncio and pyserial features, zigpy-znp will work with them.

The only real change that I'm aware of is https://github.com/pyserial/pyserial-asyncio/pull/56, but apparently the new release broke Windows support: https://github.com/pyserial/pyserial-asyncio/issues/69. May want to wait a few weeks to see if this report is valid and if other breakage occurs.

2020-12-11 16:50 UTC, puddly commented
For reference, here are all of the changes: https://github.com/pyserial/pyserial-asyncio/compare/v0.4...v0.5
The other interesting issue fixed in this release is https://github.com/pyserial/pyserial-asyncio/issues/53. I'm not sure what the consequences are of making all writes async like this, since to me it seems like this may introduce timing glitches due to the old behavior essentially passing through writes to the underlying `serial` object synchronously if there was no other buffered data.

Have you tested these new package versions under load? I'll have to do this with zigpy-znp.

2020-12-11 17:14 UTC, Adminiuga commented
running in my prod for a few days. haven't noticed anything abnormal, but it is well below heavy load.

2020-12-14 11:11 UTC, Hedda commented
> zigpy-znp doesn't depend on a specific version of these packages so can you change the `==` to `>=`?

Changed from == to >= for pyserial 3.5 and pyserial-asyncio 0.5

2020-12-14 11:26 UTC, Hedda commented
> I dont want to pin specific version

Did the PR https://github.com/home-assistant/core/pull/44089 not in effect pin these to specific versions in Home Assistant?

2021-01-03 17:07 UTC, closed without merging