Fix typo and mention slaesh cc2652 stick
zigpy/zigpy-znp pull request #60
Opened 2021-01-20 16:22 UTC by Hedda

Fix typo for Z-Stack 3.10.00.78 instead of Z-Stack 4.10.00.78 and mention Slaesh cc2652 stick too as  https://github.com/slaesh/cc2652-stick/issues/1

2021-01-21 21:08 UTC, puddly requested changes

2021-01-21 21:08 UTC, puddly commented on README.md
> - - (**STABLE**) [Electrolama's zig-a-zig-ah!](https://electrolama.com/projects/zig-a-zig-ah/) running [Z-Stack 4.10.00.78](https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_
This isn't actually a typo, Z-Stack 4.10+ is still considered "Z-Stack 3". The current release is 4.40.00.44, which is what I'm using.

2021-01-22 07:28 UTC, Hedda commented on README.md
> - - (**STABLE**) [Electrolama's zig-a-zig-ah!](https://electrolama.com/projects/zig-a-zig-ah/) running [Z-Stack 4.10.00.78](https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_
OK will close and open new PR which only adds link to [Slaesh CC2652R dongle](https://slae.sh/projects/cc2652/)

2021-01-22 07:28 UTC, Hedda commented
Will close and open new PR which only adds link to [Slaesh CC2652R dongle](https://slae.sh/projects/cc2652/)

2021-01-22 07:28 UTC, closed without merging