Update README.md with a list of all compatible hardware
zigpy/zigpy-znp pull request #69
Opened 2021-03-31 07:51 UTC by Hedda

Update README.md for zigpy-znp with list of all compatible hardware as plan is to remove such a list from zigpy in https://github.com/zigpy/zigpy/pull/705

Downstream project(s) also want such information to be provided by upstream as per https://github.com/home-assistant/home-assistant.io/pull/17089

2021-03-31 08:08 UTC, MattWestb commented
Great work !!

I can recommending putting the most detailed information i the Zigpy Wiki under respective coordinator and if its very long then making it folding parts so not being 3 pages for every device that normal user dont reading.

Today is most information in the "Coordinator Firmware Updates" but perhaps doing one page for every "family" of coordinators like "Supported coordinators zigpy-cc", "Supported coordinators EZSP" and so on if like making it little more spacey.

2021-04-07 22:39 UTC, puddly requested changes

2021-04-07 22:39 UTC, puddly commented on README.md
> + - [CC2652P/CC2652R/CC2652RB USB stick and dev board hardware flashed with Z-Stack firmware](https://www.zigbee2mqtt.io/information/supported_adapters)
Can you remove the duplicate links to Z2M's documentation and the "*hardware flashed with Z-Stack firmware*" suffix? I think it's enough to mention that all adapters supported by Z2M are supported by zigpy-znp and then just list the models.

2021-04-15 20:18 UTC, merged

2021-04-15 20:18 UTC, puddly commented
Thanks!